#file: noinspection SpellCheckingInspection
version: '3.8'

services:
  api-gateway-core:
    build: ./Gateway-Service
    container_name: api-gateway-core-service
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis

  task-orchestration-service-core:
    build: ./Task-Orchestrator-Service
    container_name: task-orchestration-core-service
    depends_on:
      - rabbitmq
      - redis

  embedding-service-core:
    build: ./Embedding-Service
    container_name: embedding-core-service
    depends_on:
      - rabbitmq

  file-service-core:
    build: ./File-Service
    container_name: file-core-service
    depends_on:
      - rabbitmq

  grobid:
    image: lfoppiano/grobid:0.7.3
    container_name: grobid
    ports:
      - "8070:8070"

  minio:
    image: minio/minio
    container_name: mino
    command: server --console-address ":9001" --address ":9000" /data
    ports:
      - "9000:9000"
      - "9001:9001"

  weaviate:
    image: semitechnologies/weaviate
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    
  redis:
    image: redis
    ports:
      - "6379:6379"
