#file: noinspection SpellCheckingInspection
version: '3.8'

services:
  api-gateway-core:
    build: ./API-Gateway
    #container_name: api-gateway-core-service
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  task-orchestration-service-core:
    build: ./Task-Orchestration-Service
    #container_name: task-orchestration-core-service
    deploy:
        replicas: 1
    depends_on:
      - rabbitmq
      - redis

  vector-service-core:
    build: ./Vector-Service
    #container_name: vector-core-service
    deploy:
      replicas: 1
    depends_on:
      - rabbitmq

  file-service-core:
    build: ./File-Service
    #container_name: file-core-service
    depends_on:
      - rabbitmq

  grobid:
    image: grobid/grobid:0.7.3
    container_name: grobid-service
    ports:
      - "8070:8070"

  minio:
    image: minio/minio
    container_name: minio-service
    command: server --console-address ":9001" --address ":9000" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_NOTIFY_AMQP_ENABLE=on
      - MINIO_NOTIFY_AMQP_URL=amqp://admin:admin123@rabbitmq-service:5672
      - MINIO_NOTIFY_AMQP_EXCHANGE=task_orchestrator_exchange
      - MINIO_NOTIFY_AMQP_ROUTING_KEY=minio_message
      - MINIO_NOTIFY_AMQP_EXCHANGE_TYPE=direct

  weaviate:
    image: semitechnologies/weaviate
    container_name: weaviate-service
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123

  postgres:
    image: postgres
    container_name: postgres-service
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=files
    
  redis:
    image: redis
    container_name: redis-service
    ports:
      - "6379:6379"
