jobs:
  generate_presigned_url_upload:
    tasks:
      - "generate_presigned_url_upload"
      - "RETURN"
      - "END"

  process_file:
    tasks:
      - "process_file"
      - "add_entries"
      - "END"

  get_files:
    tasks:
      - "get_files"
      - "RETURN"
      - "END"

  retrieve_context:
    tasks:
      - "retrieve_context"
      - "RETURN"
      - "END"

  answer_question:
    tasks:
      - "retrieve_context"
      - "chat_completion"
      - "RETURN"
      - "END"
