jobs:
  generate_presigned_url_upload:
    tasks:
      - "generate_presigned_url_upload"
      - "RETURN"
      - "END"

  process_file:
    tasks:
      - "process_file"
      - "END"

  embed_store_text:
    tasks:
      - "generate_embeddings"
      - "store_embedding"
      - "END"

  get_files:
    tasks:
      - "get_files"
      - "RETURN"
      - "END"

  answer_question:
    tasks:
      - "generate_embeddings"
      - "retrieve_closest_entries"
      - "rerank_text"
      - "chat_completion"
      - "RETURN"
      - "END"

  embed_text:
    tasks:
      - "generate_embeddings"
      - "RETURN"
      - "END"

  rerank_text:
    tasks:
      - "rerank_text"
      - "RETURN"
      - "END"

  retrieve_closest_entries:
    tasks:
      - "retrieve_closest_entries"
      - "RETURN"
      - "END"

  retrieve_query_context:
    tasks:
      - "generate_embeddings"
      - "retrieve_closest_entries"
      - "rerank_text"
      - "RETURN"
      - "END"
