jobs:
  generate_presigned_url_upload:
    tasks:
      - "generate_presigned_url_upload"
      - "RETURN"
      - "END"

  process_file:
    tasks:
      - "process_file"
      - "END"

  embed_text:
    tasks:
      - "generate_embeddings"
      - "RETURN"
      - "END"

  rerank_text:
    tasks:
      - "rerank_text"
      - "RETURN"
      - "END"

  answer_question:
    tasks:
      - "generate_embeddings"
      - "get_similar_text"
      - "rerank_text"
      - "RETURN"
      - "END"