jobs:
  get_presigned_url:
    tasks:
      - "get_presigned_url"
      - "RETURN"
      - "END"

  process_file:
    tasks:
      - "process_file_grobid"
      - "store_text_weaviate"
      - "END"

  embed_text:
    tasks:
      - "generate_embeddings"
      - "RETURN"
      - "END"

  rerank_text:
    tasks:
      - "rerank_text"
      - "RETURN"
      - "END"

  answer_question:
    tasks:
      - "generate_embeddings"
      - "get_similar_text"
      - "rerank_text"
      - "RETURN"
      - "END"