apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-core-deployment
  labels:
    app: api-gateway-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-core
  template:
    metadata:
      labels:
        app: api-gateway-core
    spec:
      containers:
      - name: api-gateway-core
        image: documentlookup.azurecr.io/api-gateway-api:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: acr-secret