apiVersion: v1
kind: Service
metadata:
  name: api-gateway-core-service
spec:
  selector:
    app: api-gateway-core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer