apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-orchestration-service-deployment
  labels:
    app: task-orchestration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-orchestration-service
  template:
    metadata:
      labels:
        app: task-orchestration-service
    spec:
      containers:
      - name: task-orchestration-service
        image: documentlookup.azurecr.io/task-orchestration-service-api:dev
        imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-secret