apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-service-core-deployment
  labels:
    app: vector-service-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-service-core
  template:
    metadata:
      labels:
        app: vector-service-core
    spec:
      containers:
      - name: vector-service-core
        image: documentlookup.azurecr.io/vector-service-core:latest
        imagePullPolicy: Always
      imagePullSecrets:
        - name: acr-secret